#!/bin/sh
terraform fmt -check -recursive
if [ $? -ne 0 ]; then
    echo "Terraform formatting errors found! Fix them before committing."
    exit 1
fi

terraform validate
if [ $? -ne 0 ]; then
    echo "Terraform validation failed! Fix errors before committing."
    exit 1
fi

tflint
if [ $? -ne 0 ]; then
    echo "Terraform linting issues found! Fix them before committing."
    exit 1
fi
